name: Masters
author: iPhysX
version: 1.0
main: com.ftbmasters.Masters
commands:
  masters:
    usage: /masters
    description: Masters related commands (OP)
  tell:
    usage: /tell
    description: Tell related commands
  slap:
    usage: /slap <player>
    description: Slaps a player
  reload:
    usage: /reload || /rl
    description: Reloads the Masters Plugin
    alias: [rl]