name: Masters
author: iPhysX
version: 1.0
main: com.ftbmasters.Masters
commands:
  masters:
    usage: /masters
    description: Masters related commands (OP)
  masters:
    class: com.ftbmasters.commands.CommandMaster
    description: Masters related commands (OP)
    usage: /<command>
  slap:
    class: com.ftbmasters.commands.CommandSlap
    usage: /<command> <player>
    description: Slaps a player
  tell:
    class: com.ftbmasters.commands.CommandTell
    usage: /<command>
    aliases: [w, t, msg]
    description: Tell related commands
