name: Masters
author: iPhysX
version: 1.0
main: com.ftbmasters.Masters
softdepend: [Reloader]
commands:
  masters:
    class: com.ftbmasters.commands.CommandMaster
    description: Masters related commands (OP)
    usage: /<command>
  slap:
    class: com.ftbmasters.commands.CommandSlap
    usage: /<command> <player>
    description: Slaps a player
  tell:
    class: com.ftbmasters.commands.CommandTell
    usage: /<command>
    aliases: [w, t, msg]
    description: Tell related commands
  reload:
    usage: /reload || /rl
    description: Reloads the Masters Plugin
    alias: [rl]